# =========================================================
# CONFIGURAÇÕES GERAIS DO HUNails
# =========================================================
spring.application.name=HUnails_backend

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.testWhileIdle=true
spring.datasource.validationQuery=SELECT 1

# Formatação de Datas (Padrão Brasil)
spring.jackson.date-format=dd/MM/yyyy
spring.jackson.time-zone=America/Sao_Paulo

# =========================================================
# SEGURANÇA (JWT)
# =========================================================
# Tenta ler do painel Discloud, se não achar, usa o padrão abaixo
jwt.secret=${JWT_SECRET:UmaChaveSecretaMuitoLongaQueVoceDeveTrocarPorAlgoSeguro12345678901234567890}
jwt.expiration=86400000
app.security.enabled=true

# =========================================================
# CONEXÃO COM POSTGRESQL (DISCLOUD DIAMOND)
# =========================================================
# O Spring vai injetar os valores que você colocou no painel da Discloud
spring.datasource.url=jdbc:postgresql://postgresql:5432/mydbhu
spring.datasource.username=davs
spring.datasource.password=sh3v100p

# Driver e Dialeto para PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# =========================================================
# LOGS E DEBUG
# =========================================================
logging.level.org.hibernate.type.descriptor.sql=TRACE
logging.level.com.example.manicure_backend=DEBUG

# Desativa o H2 Console (Não é necessário em produção)
spring.h2.console.enabled=false